apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-executor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-executor
  template:
    metadata:
      labels:
        app: pod-executor
    spec: 
      containers:
      - name: pod-executor
        image: //TODO
        ports:
          -containerPort:8080