apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec: 
      containers:
      - name: mycontainer
        image: nginx:stable
      serviceAccountName: pod-executor