apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-executor
roleRef:
  kind: ClusterRole
  name: pod-exec-cluster-role
  apiGroup: rbac.authorization.k8s.io