apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-executor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-executor
  template:
    metadata:
      labels:
        app: pod-executor
    spec: 
      serviceAccountName: pod-executor
      containers:
      - name: pod-executor
        image: smritidahal/pod-executor:latest
        ports:
          - containerPort: 8080
        env:
        - name: NUM_PODS_TO_CREATE
          value: "100"
        - name: DURATION_IN_MINUTES
          value: "5"