apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-pod
spec:
  containers:
  - name: cpu-intensive-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do :; done"]
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"
